"""
标的配置文件
定义所有追踪标的的元数据，区分个股与ETF
共 31 个标的: 个股 8 + 非杠杆ETF 7 + 杠杆/反向ETF 16
"""

TICKERS = {
    # ─── 个股 (Stocks) ─── 8只 ────────────────────────────
    "RKLB": {
        "name": "Rocket Lab Corp",
        "yf_symbol": "RKLB",
        "type": "stock",
        "market": "US",
        "sector": "航天/国防",
        "currency": "USD",
        "description": "全球领先的小型运载火箭及航天系统公司",
    },
    "NVDA": {
        "name": "NVIDIA Corp",
        "yf_symbol": "NVDA",
        "type": "stock",
        "market": "US",
        "sector": "半导体/AI",
        "currency": "USD",
        "description": "全球AI基础设施龙头，数据中心GPU市占率超80%",
    },
    "SNDK": {
        "name": "Sandisk Corp",
        "yf_symbol": "SNDK",
        "type": "stock",
        "market": "US",
        "sector": "存储/NAND",
        "currency": "USD",
        "description": "全球NAND闪存存储领导者，2024年从西部数据分拆独立上市",
    },
    "MU": {
        "name": "Micron Technology",
        "yf_symbol": "MU",
        "type": "stock",
        "market": "US",
        "sector": "半导体/存储",
        "currency": "USD",
        "description": "全球第三大存储芯片厂商，DRAM/NAND/HBM核心供应商",
    },
    "LITE": {
        "name": "Lumentum Holdings",
        "yf_symbol": "LITE",
        "type": "stock",
        "market": "US",
        "sector": "光通信/光子",
        "currency": "USD",
        "description": "光通信与光子学技术领导者，数据中心光模块核心供应商",
    },
    "00005.HK": {
        "name": "汇丰控股",
        "yf_symbol": "0005.HK",
        "type": "stock",
        "market": "HK",
        "sector": "银行/金融",
        "currency": "HKD",
        "description": "全球最大银行之一，总资产3万亿美元",
        "static_overrides": {
            "pe": 9.2, "roe": 14.8, "revenueGrowth": 3.2, "profitMargin": 28.5,
            "beta": 0.65, "marketCap": "2.23T HKD", "revenue": "65.9B USD",
            "eps": "7.21 USD", "nextEarnings": "2026-05-05",
        },
    },
    "09988.HK": {
        "name": "阿里巴巴",
        "yf_symbol": "9988.HK",
        "type": "stock",
        "market": "HK",
        "sector": "互联网/电商",
        "currency": "HKD",
        "description": "中国最大电商平台及云计算服务商，业务覆盖零售、云、物流、本地生活",
        "static_overrides": {
            "pe": 18.5, "roe": 12.3, "revenueGrowth": 8.5, "profitMargin": 11.2,
            "beta": 0.85, "marketCap": "2.1T HKD",
        },
    },
    "03986.HK": {
        "name": "中国能源建设",
        "yf_symbol": "3986.HK",
        "type": "stock",
        "market": "HK",
        "sector": "能源/基建",
        "currency": "HKD",
        "description": "中国能源基础设施建设龙头，覆盖电力、新能源、城市基建",
        "static_overrides": {
            "pe": 7.5, "roe": 6.8, "revenueGrowth": 5.1, "profitMargin": 3.2,
            "beta": 0.55,
        },
    },

    # ─── 非杠杆 ETF ─── 7只 ──────────────────────────────
    "DRAM": {
        "name": "Roundhill Memory ETF",
        "yf_symbol": "DRAM",
        "type": "etf",
        "etf_type": "主题ETF",
        "market": "US",
        "sector": "存储/ETF",
        "currency": "USD",
        "leverage": None,
        "benchmark": "主动管理 - 无跟踪指数",
        "issuer": "Roundhill Investments",
        "dividend_policy": "暂不分红",
        "inception_date": "2026-04-02",
        "description": "首只存储芯片主题ETF，覆盖全球HBM、DRAM、NAND存储龙头",
        "static_overrides": {
            "expenseRatio": 0.65,
            "topHoldings": [
                {"name": "Samsung Electronics", "weight": 25.02},
                {"name": "Micron Technology", "weight": 24.13},
                {"name": "SK Hynix", "weight": 23.61},
                {"name": "Kioxia Holdings", "weight": 4.98},
                {"name": "SanDisk Corp", "weight": 4.65},
            ],
            "concentrationTop3": 72.76,
            "totalHoldings": 9,
        },
    },
    "IYZ": {
        "name": "iShares U.S. Telecom ETF",
        "yf_symbol": "IYZ",
        "type": "etf",
        "etf_type": "行业ETF",
        "market": "US",
        "sector": "电信/通信",
        "currency": "USD",
        "leverage": None,
        "benchmark": "Dow Jones U.S. Select Telecommunications Index",
        "issuer": "iShares (BlackRock)",
        "dividend_policy": "季度分红",
        "description": "追踪美国电信行业指数，覆盖AT&T、Verizon等通信龙头",
    },
    "MARS": {
        "name": "Roundhill MARS ETF",
        "yf_symbol": "MARS",
        "type": "etf",
        "etf_type": "主题ETF",
        "market": "US",
        "sector": "航天/机器人",
        "currency": "USD",
        "leverage": None,
        "benchmark": "主动管理",
        "issuer": "Roundhill Investments",
        "description": "覆盖机器人、自动化、火星探索、太空经济相关公司",
    },
    "UFO": {
        "name": "Procure Space ETF",
        "yf_symbol": "UFO",
        "type": "etf",
        "etf_type": "主题ETF",
        "market": "US",
        "sector": "太空/卫星",
        "currency": "USD",
        "leverage": None,
        "benchmark": "S-Network Space Index",
        "issuer": "Procure",
        "description": "全球太空经济ETF，覆盖卫星通信、火箭发射、太空基础设施",
    },
    "IGV": {
        "name": "iShares Expanded Tech-Software ETF",
        "yf_symbol": "IGV",
        "type": "etf",
        "etf_type": "行业ETF",
        "market": "US",
        "sector": "软件/SaaS",
        "currency": "USD",
        "leverage": None,
        "benchmark": "S&P North American Expanded Technology Software Index",
        "issuer": "iShares (BlackRock)",
        "description": "追踪北美科技软件行业，覆盖Microsoft、Salesforce、Adobe等",
    },
    "EWY": {
        "name": "iShares MSCI South Korea ETF",
        "yf_symbol": "EWY",
        "type": "etf",
        "etf_type": "国家ETF",
        "market": "US",
        "sector": "韩国/综合",
        "currency": "USD",
        "leverage": None,
        "benchmark": "MSCI Korea 25/50 Index",
        "issuer": "iShares (BlackRock)",
        "description": "追踪韩国市场，重仓三星电子、SK海力士等半导体股",
    },
    "03486.HK": {
        "name": "华夏恒生科技ETF",
        "yf_symbol": "3486.HK",
        "type": "etf",
        "etf_type": "指数ETF",
        "market": "HK",
        "sector": "恒生科技",
        "currency": "HKD",
        "leverage": None,
        "benchmark": "恒生科技指数",
        "issuer": "华夏基金(香港)",
        "description": "追踪恒生科技指数，覆盖腾讯、阿里、美团等港股科技龙头",
        "static_overrides": {
            "expenseRatio": 0.60,
        },
    },

    # ─── 杠杆/反向 ETF ─── 16只 ──────────────────────────
    "TQQQ": {
        "name": "ProShares UltraPro QQQ",
        "yf_symbol": "TQQQ",
        "type": "etf",
        "etf_type": "3倍杠杆ETF",
        "market": "US",
        "sector": "纳斯达克/杠杆",
        "currency": "USD",
        "leverage": "3x",
        "benchmark": "NASDAQ-100 每日3倍",
        "issuer": "ProShares",
        "description": "追踪纳斯达克100指数每日3倍表现，最受欢迎的杠杆ETF之一",
    },
    "SOXL": {
        "name": "Direxion Daily Semiconductor Bull 3X",
        "yf_symbol": "SOXL",
        "type": "etf",
        "etf_type": "3倍杠杆ETF",
        "market": "US",
        "sector": "半导体/杠杆",
        "currency": "USD",
        "leverage": "3x",
        "benchmark": "PHLX Semiconductor Index 每日3倍",
        "issuer": "Direxion",
        "description": "追踪费城半导体指数每日3倍表现，半导体行业高倍杠杆工具",
    },
    "YINN": {
        "name": "Direxion Daily FTSE China Bull 3X",
        "yf_symbol": "YINN",
        "type": "etf",
        "etf_type": "3倍杠杆ETF",
        "market": "US",
        "sector": "中国/杠杆",
        "currency": "USD",
        "leverage": "3x",
        "benchmark": "FTSE China 50 Index 每日3倍",
        "issuer": "Direxion",
        "description": "追踪富时中国50指数每日3倍表现，中概股杠杆交易工具",
    },
    "KORU": {
        "name": "Direxion Daily South Korea Bull 3X",
        "yf_symbol": "KORU",
        "type": "etf",
        "etf_type": "3倍杠杆ETF",
        "market": "US",
        "sector": "韩国/杠杆",
        "currency": "USD",
        "leverage": "3x",
        "benchmark": "MSCI Korea 25/50 每日3倍",
        "issuer": "Direxion",
        "description": "追踪韩国MSCI指数每日3倍表现，韩国市场杠杆交易工具",
    },
    "CWEB": {
        "name": "Direxion Daily CSI China Internet Bull 2X",
        "yf_symbol": "CWEB",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "US",
        "sector": "中国互联网/杠杆",
        "currency": "USD",
        "leverage": "2x",
        "benchmark": "CSI Overseas China Internet Index 每日2倍",
        "issuer": "Direxion",
        "description": "追踪中国海外互联网指数每日2倍表现，覆盖阿里、腾讯、京东等",
    },
    "UGL": {
        "name": "ProShares Ultra Gold",
        "yf_symbol": "UGL",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "US",
        "sector": "黄金/杠杆",
        "currency": "USD",
        "leverage": "2x",
        "benchmark": "Bloomberg Gold Subindex 每日2倍",
        "issuer": "ProShares",
        "description": "追踪黄金价格每日2倍表现，贵金属杠杆投资工具",
    },
    "SCO": {
        "name": "ProShares UltraShort Bloomberg Crude Oil",
        "yf_symbol": "SCO",
        "type": "etf",
        "etf_type": "2倍反向ETF",
        "market": "US",
        "sector": "原油/反向",
        "currency": "USD",
        "leverage": "-2x",
        "benchmark": "Bloomberg Crude Oil Subindex 每日-2倍",
        "issuer": "ProShares",
        "description": "追踪原油价格每日反向2倍，用于做空或对冲油价风险",
    },
    "SNXX": {
        "name": "ProShares Ultra Semiconductors",
        "yf_symbol": "SNXX",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "US",
        "sector": "半导体/杠杆",
        "currency": "USD",
        "leverage": "2x",
        "benchmark": "Dow Jones U.S. Semiconductors Index 每日2倍",
        "issuer": "ProShares",
        "description": "追踪道琼斯美国半导体指数每日2倍表现",
    },
    "BABX": {
        "name": "GraniteShares 2x Long BABA ETF",
        "yf_symbol": "BABX",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "US",
        "sector": "阿里巴巴/杠杆",
        "currency": "USD",
        "leverage": "2x",
        "benchmark": "Alibaba ADR 每日2倍",
        "issuer": "GraniteShares",
        "description": "追踪阿里巴巴ADR每日2倍表现，单票杠杆ETF",
    },
    "RKLX": {
        "name": "GraniteShares 2x Long RKLB ETF",
        "yf_symbol": "RKLX",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "US",
        "sector": "航天/杠杆",
        "currency": "USD",
        "leverage": "2x",
        "benchmark": "Rocket Lab ADR 每日2倍",
        "issuer": "GraniteShares",
        "description": "追踪Rocket Lab每日2倍表现，单票杠杆ETF",
    },
    "07709.HK": {
        "name": "南方两倍做多海力士",
        "yf_symbol": "7709.HK",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "HK",
        "sector": "存储/杠杆ETF",
        "currency": "HKD",
        "leverage": "2x",
        "benchmark": "SK Hynix (KRX:000660) 每日2倍",
        "issuer": "CSOP Asset Management",
        "dividend_policy": "不分红",
        "inception_date": "2025-10-16",
        "description": "CSOP发行的2倍杠杆ETF，追踪SK海力士每日表现",
        "static_overrides": {
            "expenseRatio": 2.00,
            "nav": 25.37,
            "topHoldings": [{"name": "SK Hynix 掉期合约", "weight": 100}],
            "concentrationTop3": 100,
            "totalHoldings": 1,
        },
    },
    "07299.HK": {
        "name": "南方两倍做多三星",
        "yf_symbol": "7299.HK",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "HK",
        "sector": "半导体/杠杆ETF",
        "currency": "HKD",
        "leverage": "2x",
        "benchmark": "Samsung Electronics 每日2倍",
        "issuer": "CSOP Asset Management",
        "description": "追踪三星电子每日2倍表现，覆盖存储+晶圆代工+消费电子",
        "static_overrides": {"expenseRatio": 2.00},
    },
    "07200.HK": {
        "name": "南方两倍做多腾讯",
        "yf_symbol": "7200.HK",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "HK",
        "sector": "互联网/杠杆ETF",
        "currency": "HKD",
        "leverage": "2x",
        "benchmark": "Tencent Holdings 每日2倍",
        "issuer": "CSOP Asset Management",
        "description": "追踪腾讯控股每日2倍表现",
        "static_overrides": {"expenseRatio": 1.50},
    },
    "07747.HK": {
        "name": "南方两倍做多NVDA",
        "yf_symbol": "7747.HK",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "HK",
        "sector": "半导体/杠杆ETF",
        "currency": "HKD",
        "leverage": "2x",
        "benchmark": "NVIDIA Corp 每日2倍",
        "issuer": "CSOP Asset Management",
        "description": "追踪NVIDIA每日2倍表现，港股AI杠杆工具",
        "static_overrides": {"expenseRatio": 1.50},
    },
    "07552.HK": {
        "name": "南方两倍做空恒生科技",
        "yf_symbol": "7552.HK",
        "type": "etf",
        "etf_type": "2倍反向ETF",
        "market": "HK",
        "sector": "恒生科技/反向",
        "currency": "HKD",
        "leverage": "-2x",
        "benchmark": "恒生科技指数 每日-2倍",
        "issuer": "CSOP Asset Management",
        "description": "追踪恒生科技指数每日反向2倍，用于做空港股科技板块",
        "static_overrides": {"expenseRatio": 1.50},
    },
    "07234.HK": {
        "name": "南方两倍做多美团",
        "yf_symbol": "7234.HK",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "HK",
        "sector": "本地生活/杠杆ETF",
        "currency": "HKD",
        "leverage": "2x",
        "benchmark": "Meituan 每日2倍",
        "issuer": "CSOP Asset Management",
        "description": "追踪美团每日2倍表现，本地生活杠杆投资工具",
        "static_overrides": {"expenseRatio": 1.50},
    },
}

# 板块-ETF映射（扩展版）
SECTOR_ETF_MAP = {
    "半导体":   {"etf": "SMH",  "name": "VanEck Semiconductor ETF"},
    "存储":     {"etf": "DRAM", "name": "Roundhill Memory ETF"},
    "航天":     {"etf": "UFO",  "name": "Procure Space ETF"},
    "银行":     {"etf": "XLF",  "name": "Financial Select SPDR"},
    "AI":       {"etf": "BOTZ", "name": "Global X Robotics & AI ETF"},
    "软件":     {"etf": "IGV",  "name": "iShares Expanded Tech-Software ETF"},
    "韩国":     {"etf": "EWY",  "name": "iShares MSCI South Korea ETF"},
    "电信":     {"etf": "IYZ",  "name": "iShares U.S. Telecom ETF"},
    "中国互联网": {"etf": "KWEB", "name": "KraneShares CSI China Internet ETF"},
    "黄金":     {"etf": "GLD",  "name": "SPDR Gold Shares"},
    "原油":     {"etf": "USO",  "name": "United States Oil Fund"},
    "恒生科技": {"etf": "03486.HK", "name": "华夏恒生科技ETF"},
    "光通信":   {"etf": "FCOM", "name": "Fidelity MSCI Communication Services ETF"},
    "能源":     {"etf": "XLE",  "name": "Energy Select SPDR"},
    "机器人":   {"etf": "MARS", "name": "Roundhill MARS ETF"},
}
