"""
标的配置文件
定义所有追踪标的的元数据，区分个股与ETF
"""

TICKERS = {
    # ═══════════════════════════════════════════════════════════
    #  个股 (Stocks)
    # ═══════════════════════════════════════════════════════════

    "RKLB": {
        "name": "Rocket Lab Corp",
        "yf_symbol": "RKLB",
        "type": "stock",
        "market": "US",
        "sector": "航天/国防",
        "currency": "USD",
        "description": "全球领先的小型运载火箭及航天系统公司",
    },
    "NVDA": {
        "name": "NVIDIA Corp",
        "yf_symbol": "NVDA",
        "type": "stock",
        "market": "US",
        "sector": "半导体/AI",
        "currency": "USD",
        "description": "全球AI基础设施龙头，数据中心GPU市占率超80%",
    },
    "SNDK": {
        "name": "Sandisk Corp",
        "yf_symbol": "SNDK",
        "type": "stock",
        "market": "US",
        "sector": "存储/NAND",
        "currency": "USD",
        "description": "全球NAND闪存存储领导者，2024年从西部数据分拆独立上市",
    },
    "MU": {
        "name": "Micron Technology",
        "yf_symbol": "MU",
        "type": "stock",
        "market": "US",
        "sector": "半导体/存储",
        "currency": "USD",
        "description": "全球第三大存储芯片厂商，DRAM/NAND/HBM核心供应商",
    },
    "LITE": {
        "name": "Lumentum Holdings",
        "yf_symbol": "LITE",
        "type": "stock",
        "market": "US",
        "sector": "光通信/激光",
        "currency": "USD",
        "description": "光通信器件及商业激光领导者，3D传感和数据中心光模块核心供应商",
    },

    # ─── 港股个股 ──────────────────────────────────────────────
    "00005.HK": {
        "name": "汇丰控股",
        "yf_symbol": "0005.HK",
        "futu_symbol": "HK.00005",
        "type": "stock", "market": "HK", "sector": "银行/金融", "currency": "HKD",
        "description": "全球最大银行之一，总资产3万亿美元",
        "static_overrides": {
            "pe": 9.2, "roe": 14.8, "revenueGrowth": 3.2, "profitMargin": 28.5,
            "beta": 0.65, "marketCap": "2.23T HKD", "revenue": "65.9B USD",
            "eps": "7.21 USD", "nextEarnings": "2026-05-05",
        },
    },
    "09988.HK": {
        "name": "阿里巴巴-W",
        "yf_symbol": "9988.HK",
        "futu_symbol": "HK.09988",
        "type": "stock", "market": "HK", "sector": "电商/科技", "currency": "HKD",
        "description": "中国最大电商及云计算平台，旗下淘宝天猫阿里云等",
    },
    "03986.HK": {
        "name": "兆易创新",
        "yf_symbol": "3986.HK",
        "futu_symbol": "HK.03986",
        "type": "stock", "market": "HK", "sector": "半导体/MCU", "currency": "HKD",
        "description": "国产NOR Flash及MCU龙头，存储+微控制器双轮驱动",
    },

    # ─── A股个股 ──────────────────────────────────────────────
    "600519.SH": {
        "name": "贵州茅台",
        "yf_symbol": "600519.SS",
        "futu_symbol": "SH.600519",
        "type": "stock", "market": "SH", "sector": "白酒/消费", "currency": "CNY",
        "description": "中国高端白酒龙头，市值长期位居A股前列",
    },
    "000333.SZ": {
        "name": "美的集团",
        "yf_symbol": "000333.SZ",
        "futu_symbol": "SZ.000333",
        "type": "stock", "market": "SZ", "sector": "家电/智能制造", "currency": "CNY",
        "description": "全球家电龙头，业务延伸至工业机器人和楼宇科技",
    },
    "300750.SZ": {
        "name": "宁德时代",
        "yf_symbol": "300750.SZ",
        "futu_symbol": "SZ.300750",
        "type": "stock", "market": "SZ", "sector": "新能源/动力电池", "currency": "CNY",
        "description": "全球最大动力电池制造商，市占率长期领先",
    },

    # ─── 韩股个股 ─────────────────────────────────────────────
    "005930.KS": {
        "name": "三星电子",
        "yf_symbol": "005930.KS",
        "type": "stock", "market": "KR", "sector": "半导体/存储", "currency": "KRW",
        "description": "全球最大存储芯片厂商，DRAM/NAND双料龙头，兼营智能手机/显示面板",
    },
    "000660.KS": {
        "name": "SK海力士",
        "yf_symbol": "000660.KS",
        "type": "stock", "market": "KR", "sector": "半导体/HBM", "currency": "KRW",
        "description": "全球第二大DRAM厂商，HBM高带宽存储核心供应商，AI算力受益标的",
    },

    # ─── 日股个股 ─────────────────────────────────────────────
    "7203.T": {
        "name": "丰田汽车",
        "yf_symbol": "7203.T",
        "type": "stock", "market": "JP", "sector": "汽车/混动", "currency": "JPY",
        "description": "全球最大汽车制造商，混动技术领跑，纯电转型加速",
    },
    "6758.T": {
        "name": "索尼集团",
        "yf_symbol": "6758.T",
        "type": "stock", "market": "JP", "sector": "电子/娱乐", "currency": "JPY",
        "description": "全球图像传感器龙头，PlayStation/影视/音乐多元业务",
    },
    "8035.T": {
        "name": "东京电子",
        "yf_symbol": "8035.T",
        "type": "stock", "market": "JP", "sector": "半导体/设备", "currency": "JPY",
        "description": "全球前三大半导体设备厂商，刻蚀/涂胶显影核心供应商",
    },

    # ═══════════════════════════════════════════════════════════
    #  ETF — 非杠杆
    # ═══════════════════════════════════════════════════════════

    "DRAM": {
        "name": "Roundhill Memory ETF",
        "yf_symbol": "DRAM",
        "type": "etf",
        "etf_type": "主题ETF",
        "market": "US",
        "sector": "存储/ETF",
        "currency": "USD",
        "leverage": None,
        "benchmark": "主动管理 - 无跟踪指数",
        "issuer": "Roundhill Investments",
        "dividend_policy": "暂不分红",
        "inception_date": "2026-04-02",
        "description": "首只存储芯片主题ETF，覆盖全球HBM、DRAM、NAND存储龙头",
        "static_overrides": {
            "expenseRatio": 0.65,
            "topHoldings": [
                {"name": "Samsung Electronics", "weight": 25.02},
                {"name": "Micron Technology", "weight": 24.13},
                {"name": "SK Hynix", "weight": 23.61},
                {"name": "Kioxia Holdings", "weight": 4.98},
                {"name": "SanDisk Corp", "weight": 4.65},
            ],
            "concentrationTop3": 72.76,
            "totalHoldings": 9,
        },
    },
    "IYZ": {
        "name": "iShares U.S. Telecom ETF",
        "yf_symbol": "IYZ",
        "type": "etf",
        "etf_type": "行业ETF",
        "market": "US",
        "sector": "电信/通信",
        "currency": "USD",
        "leverage": None,
        "benchmark": "Dow Jones U.S. Select Telecommunications",
        "issuer": "iShares (BlackRock)",
        "dividend_policy": "季度分红",
        "inception_date": "2000-05-22",
        "description": "跟踪美国电信行业，涵盖AT&T、Verizon等通信龙头",
    },
    "MARS": {
        "name": "Roundhill MARS ETF",
        "yf_symbol": "MARS",
        "type": "etf",
        "etf_type": "主题ETF",
        "market": "US",
        "sector": "航天/太空",
        "currency": "USD",
        "leverage": None,
        "benchmark": "主动管理",
        "issuer": "Roundhill Investments",
        "dividend_policy": "暂不分红",
        "inception_date": "2025-01-01",
        "description": "Roundhill太空探索主题ETF，覆盖航天、卫星和太空经济",
    },
    "UFO": {
        "name": "Procure Space ETF",
        "yf_symbol": "UFO",
        "type": "etf",
        "etf_type": "主题ETF",
        "market": "US",
        "sector": "航天/太空",
        "currency": "USD",
        "leverage": None,
        "benchmark": "S-Network Space Index",
        "issuer": "Procure ETFs",
        "dividend_policy": "季度分红",
        "inception_date": "2019-04-11",
        "description": "全球太空经济ETF，涵盖卫星通信、火箭发射、地球观测等",
    },
    "IGV": {
        "name": "iShares Expanded Tech-Software ETF",
        "yf_symbol": "IGV",
        "type": "etf",
        "etf_type": "行业ETF",
        "market": "US",
        "sector": "软件/科技",
        "currency": "USD",
        "leverage": None,
        "benchmark": "S&P North American Expanded Technology Software",
        "issuer": "iShares (BlackRock)",
        "dividend_policy": "季度分红",
        "inception_date": "2001-07-10",
        "description": "北美科技软件行业ETF，覆盖微软、Salesforce、Adobe等软件龙头",
    },
    "EWY": {
        "name": "iShares MSCI South Korea ETF",
        "yf_symbol": "EWY",
        "type": "etf",
        "etf_type": "国家ETF",
        "market": "US",
        "sector": "韩国/综合",
        "currency": "USD",
        "leverage": None,
        "benchmark": "MSCI Korea 25/50 Index",
        "issuer": "iShares (BlackRock)",
        "dividend_policy": "半年分红",
        "inception_date": "2000-05-09",
        "description": "韩国市场旗舰ETF，覆盖三星电子、SK海力士、现代汽车等",
    },

    # ─── 港股非杠杆 ETF ───────────────────────────────────────
    "03486.HK": {
        "name": "易方达亚洲科技ETF",
        "yf_symbol": "3486.HK",
        "futu_symbol": "HK.03486",
        "type": "etf",
        "etf_type": "主题ETF",
        "market": "HK",
        "sector": "亚洲科技",
        "currency": "HKD",
        "leverage": None,
        "benchmark": "亚洲科技指数",
        "issuer": "易方达资产管理",
        "dividend_policy": "不分红",
        "inception_date": "2023-01-01",
        "description": "覆盖亚太地区科技龙头的主题ETF",
    },

    # ═══════════════════════════════════════════════════════════
    #  ETF — 杠杆/反向
    # ═══════════════════════════════════════════════════════════

    # ─── 美股杠杆 ETF ─────────────────────────────────────────
    "TQQQ": {
        "name": "ProShares UltraPro QQQ",
        "yf_symbol": "TQQQ",
        "type": "etf",
        "etf_type": "3倍杠杆ETF",
        "market": "US",
        "sector": "纳指/杠杆",
        "currency": "USD",
        "leverage": "3x",
        "benchmark": "NASDAQ-100 Index 每日3倍",
        "issuer": "ProShares",
        "dividend_policy": "季度分红",
        "inception_date": "2010-02-09",
        "description": "纳斯达克100指数3倍杠杆ETF，全球最大杠杆ETF之一",
    },
    "SOXL": {
        "name": "Direxion Daily Semiconductor Bull 3X",
        "yf_symbol": "SOXL",
        "type": "etf",
        "etf_type": "3倍杠杆ETF",
        "market": "US",
        "sector": "半导体/杠杆",
        "currency": "USD",
        "leverage": "3x",
        "benchmark": "ICE Semiconductor Index 每日3倍",
        "issuer": "Direxion",
        "dividend_policy": "季度分红",
        "inception_date": "2010-03-11",
        "description": "半导体行业3倍杠杆ETF，放大费城半导体指数日收益",
    },
    "YINN": {
        "name": "Direxion Daily FTSE China Bull 3X",
        "yf_symbol": "YINN",
        "type": "etf",
        "etf_type": "3倍杠杆ETF",
        "market": "US",
        "sector": "中国/杠杆",
        "currency": "USD",
        "leverage": "3x",
        "benchmark": "FTSE China 50 Index 每日3倍",
        "issuer": "Direxion",
        "dividend_policy": "年度分红",
        "inception_date": "2009-12-03",
        "description": "中国大盘股3倍杠杆ETF，追踪FTSE中国50指数每日3倍表现",
    },
    "KORU": {
        "name": "Direxion Daily South Korea Bull 3X",
        "yf_symbol": "KORU",
        "type": "etf",
        "etf_type": "3倍杠杆ETF",
        "market": "US",
        "sector": "韩国/杠杆",
        "currency": "USD",
        "leverage": "3x",
        "benchmark": "MSCI Korea 25/50 Index 每日3倍",
        "issuer": "Direxion",
        "dividend_policy": "年度分红",
        "inception_date": "2013-04-10",
        "description": "韩国市场3倍杠杆ETF，放大MSCI韩国指数日收益",
    },
    "CWEB": {
        "name": "Direxion Daily CSI China Internet Bull 2X",
        "yf_symbol": "CWEB",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "US",
        "sector": "中国互联网/杠杆",
        "currency": "USD",
        "leverage": "2x",
        "benchmark": "CSI Overseas China Internet Index 每日2倍",
        "issuer": "Direxion",
        "dividend_policy": "年度分红",
        "inception_date": "2016-11-02",
        "description": "中国互联网2倍杠杆ETF，覆盖阿里、腾讯、拼多多等",
    },
    "UGL": {
        "name": "ProShares Ultra Gold",
        "yf_symbol": "UGL",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "US",
        "sector": "黄金/杠杆",
        "currency": "USD",
        "leverage": "2x",
        "benchmark": "Bloomberg Gold Subindex 每日2倍",
        "issuer": "ProShares",
        "dividend_policy": "不分红",
        "inception_date": "2008-12-01",
        "description": "黄金2倍杠杆ETF，追踪彭博黄金子指数每日2倍表现",
    },
    "SCO": {
        "name": "ProShares UltraShort Crude Oil",
        "yf_symbol": "SCO",
        "type": "etf",
        "etf_type": "2倍反向ETF",
        "market": "US",
        "sector": "原油/反向",
        "currency": "USD",
        "leverage": "-2x",
        "benchmark": "Bloomberg WTI Crude Oil Subindex 每日-2倍",
        "issuer": "ProShares",
        "dividend_policy": "不分红",
        "inception_date": "2008-11-24",
        "description": "原油2倍反向ETF，做空WTI原油日表现的2倍",
    },
    "SNXX": {
        "name": "GraniteShares 2x Long SNDK Daily ETF",
        "yf_symbol": "SNXX",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "US",
        "sector": "存储/杠杆",
        "currency": "USD",
        "leverage": "2x",
        "benchmark": "SanDisk Corp (SNDK) 每日2倍",
        "issuer": "GraniteShares",
        "dividend_policy": "不分红",
        "inception_date": "2025-01-01",
        "description": "SanDisk个股2倍杠杆ETF，放大SNDK每日收益",
    },
    "BABX": {
        "name": "GraniteShares 2x Long BABA Daily ETF",
        "yf_symbol": "BABX",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "US",
        "sector": "中国科技/杠杆",
        "currency": "USD",
        "leverage": "2x",
        "benchmark": "Alibaba (BABA) 每日2倍",
        "issuer": "GraniteShares",
        "dividend_policy": "不分红",
        "inception_date": "2024-01-01",
        "description": "阿里巴巴个股2倍杠杆ETF，放大BABA每日收益",
    },
    "RKLX": {
        "name": "GraniteShares 2x Long RKLB Daily ETF",
        "yf_symbol": "RKLX",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "US",
        "sector": "航天/杠杆",
        "currency": "USD",
        "leverage": "2x",
        "benchmark": "Rocket Lab (RKLB) 每日2倍",
        "issuer": "GraniteShares",
        "dividend_policy": "不分红",
        "inception_date": "2024-06-01",
        "description": "Rocket Lab个股2倍杠杆ETF，放大RKLB每日收益",
    },

    # ─── 港股杠杆/反向 ETF ────────────────────────────────────
    "07709.HK": {
        "name": "南方两倍做多海力士",
        "yf_symbol": "7709.HK",
        "futu_symbol": "HK.07709",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "HK",
        "sector": "存储/杠杆ETF",
        "currency": "HKD",
        "leverage": "2x",
        "benchmark": "SK Hynix (KRX:000660) 每日2倍",
        "issuer": "CSOP Asset Management",
        "dividend_policy": "不分红",
        "inception_date": "2025-10-16",
        "description": "CSOP发行的2倍杠杆ETF，追踪SK海力士每日表现",
        "static_overrides": {
            "expenseRatio": 2.00,
            "nav": 25.37,
            "topHoldings": [{"name": "SK Hynix 掉期合约", "weight": 100}],
            "concentrationTop3": 100,
            "totalHoldings": 1,
            "trackingError": "较高 (杠杆损耗)",
        },
    },
    "07299.HK": {
        "name": "南方两倍做多黄金",
        "yf_symbol": "7299.HK",
        "futu_symbol": "HK.07299",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "HK",
        "sector": "黄金/杠杆ETF",
        "currency": "HKD",
        "leverage": "2x",
        "benchmark": "LBMA Gold Price AM 每日2倍",
        "issuer": "CSOP Asset Management",
        "dividend_policy": "不分红",
        "inception_date": "2024-01-01",
        "description": "港股2倍杠杆黄金ETF，追踪伦敦金每日表现的两倍",
    },
    "07200.HK": {
        "name": "南方两倍做多恒指",
        "yf_symbol": "7200.HK",
        "futu_symbol": "HK.07200",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "HK",
        "sector": "恒指/杠杆ETF",
        "currency": "HKD",
        "leverage": "2x",
        "benchmark": "恒生指数 (HSI) 每日2倍",
        "issuer": "南方东英",
        "dividend_policy": "不分红",
        "inception_date": "2016-06-16",
        "description": "港股恒生指数2倍杠杆ETF，追踪HSI每日表现",
    },
    "07747.HK": {
        "name": "南方两倍做多纳指",
        "yf_symbol": "7747.HK",
        "futu_symbol": "HK.07747",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "HK",
        "sector": "纳指/杠杆ETF",
        "currency": "HKD",
        "leverage": "2x",
        "benchmark": "NASDAQ-100 Index 每日2倍",
        "issuer": "南方东英",
        "dividend_policy": "不分红",
        "inception_date": "2023-01-01",
        "description": "港股纳斯达克100指数2倍杠杆ETF",
    },
    "07552.HK": {
        "name": "南方两倍做空纳指",
        "yf_symbol": "7552.HK",
        "futu_symbol": "HK.07552",
        "type": "etf",
        "etf_type": "2倍反向ETF",
        "market": "HK",
        "sector": "纳指/反向ETF",
        "currency": "HKD",
        "leverage": "-2x",
        "benchmark": "NASDAQ-100 Index 每日-2倍",
        "issuer": "南方东英",
        "dividend_policy": "不分红",
        "inception_date": "2023-01-01",
        "description": "港股纳斯达克100指数2倍反向ETF，做空纳指",
    },
    "07234.HK": {
        "name": "XL二博时中创业",
        "yf_symbol": "7234.HK",
        "futu_symbol": "HK.07234",
        "type": "etf",
        "etf_type": "2倍杠杆ETF",
        "market": "HK",
        "sector": "创业板/杠杆ETF",
        "currency": "HKD",
        "leverage": "2x",
        "benchmark": "创业板指数 每日2倍",
        "issuer": "博时基金",
        "dividend_policy": "不分红",
        "inception_date": "2024-01-01",
        "description": "港股创业板指数2倍杠杆ETF，追踪中国创业板每日表现",
    },
}

# 板块-ETF映射
SECTOR_ETF_MAP = {
    "半导体": {"etf": "SOXL", "name": "Direxion 3X Semiconductor"},
    "存储":   {"etf": "DRAM", "name": "Roundhill Memory ETF"},
    "航天":   {"etf": "UFO",  "name": "Procure Space ETF"},
    "银行":   {"etf": "XLF",  "name": "Financial Select SPDR"},
    "AI":     {"etf": "BOTZ", "name": "Global X Robotics & AI ETF"},
    "科技":   {"etf": "IGV",  "name": "iShares Expanded Tech-Software"},
    "韩国":   {"etf": "EWY",  "name": "iShares MSCI South Korea"},
    "中国":   {"etf": "YINN", "name": "Direxion 3X China Bull"},
    "黄金":   {"etf": "UGL",  "name": "ProShares Ultra Gold"},
    "原油":   {"etf": "SCO",  "name": "ProShares UltraShort Crude Oil"},
    "电信":   {"etf": "IYZ",  "name": "iShares U.S. Telecom"},
}
